openapi: '3.0.3'
info:
  title: Report Module
  version: '1.0'
servers:
  - url: https://merchantapi.testewallet.com
tags:
  - name: Report
security:
  - apikeyAuth: []
    XMerchantId: []
paths:
  /api/v{version}/report/customers:
    get:
      tags:
        - Report
      summary: Get Beneficiary Report
      description: This API returns matching beneficiary details based on filters applied
      operationId: get-beneficiary-report
      parameters:
        - $ref: 'openAPI/schemas/index.yml#/parameters/Version'
        - $ref: 'openAPI/schemas/index.yml#/parameters/Country'
        - $ref: 'openAPI/schemas/index.yml#/parameters/FirstName'
        - $ref: 'openAPI/schemas/index.yml#/parameters/LastName'
        - $ref: 'openAPI/schemas/index.yml#/parameters/UserName'
        - $ref: 'openAPI/schemas/index.yml#/parameters/Email'
        - $ref: 'openAPI/schemas/index.yml#/parameters/BeneficiaryTokenQuery'
        - $ref: 'openAPI/schemas/index.yml#/parameters/PageNumber'
        - $ref: 'openAPI/schemas/index.yml#/parameters/PageSize'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: 'openAPI/schemas/index.yml#/schemas/DefaultResponse'
                  - type: object
                    properties:
                      data:
                        $ref: 'openAPI/schemas/report_schemas.yml#/schemas/BeneficiaryReport'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'openAPI/schemas/index.yml#/schemas/DefaultResponse'
              example:
                isSuccess: false
                message: Invalid request
                statusCode: 400
                logIdentifier: xyz789
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: 'openAPI/schemas/index.yml#/schemas/DefaultResponse'
              example:
                isSuccess: false
                message: Internal server error
                statusCode: 500
                logIdentifier: def456
  /api/v{version}/report/transfers:
    get:
      tags:
        - Report
      summary: Get Transfer Report
      description: This API returns matching transfers details based on filters applied.
      operationId: get-transfer-report
      parameters:
        - $ref: 'openAPI/schemas/index.yml#/parameters/Version'
        - $ref: 'openAPI/schemas/index.yml#/parameters/BeneficiaryTokenQuery'
        - $ref: 'openAPI/schemas/transfer_schemas.yml#/parameters/TransferToken'
        - $ref: 'openAPI/schemas/transfer_schemas.yml#/parameters/MerchantTransactionId'
        - $ref: 'openAPI/schemas/transfer_schemas.yml#/parameters/SourceCurrency'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: 'openAPI/schemas/index.yml#/schemas/DefaultResponse'
                  - type: object
                    properties:
                      data:
                        $ref: 'openAPI/schemas/report_schemas.yml#/schemas/TransferReport'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'openAPI/schemas/index.yml#/schemas/DefaultResponse'
              example:
                isSuccess: false
                message: Invalid request
                statusCode: 400
                logIdentifier: xyz789
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: 'openAPI/schemas/index.yml#/schemas/DefaultResponse'
              example:
                isSuccess: false
                message: Internal server error
                statusCode: 500
                logIdentifier: def456
  /api/v{version}/report/{beneficiaryToken}/transfers:
    get:
      tags:
        - Report
      summary: Get Transfers Report By Beneficiary
      description: This API returns matching transfers details filtered by the beneficiary's token.
      operationId: get-transfer-report-data
      parameters:
        - $ref: 'openAPI/schemas/index.yml#/parameters/Version'
        - $ref: 'openAPI/schemas/index.yml#/parameters/BeneficiaryToken'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: 'openAPI/schemas/index.yml#/schemas/DefaultResponse'
                  - type: object
                    properties:
                      data:
                        $ref: 'openAPI/schemas/report_schemas.yml#/schemas/TransferReport'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'openAPI/schemas/index.yml#/schemas/DefaultResponse'
              example:
                isSuccess: false
                message: Invalid request
                statusCode: 400
                logIdentifier: xyz789
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: 'openAPI/schemas/index.yml#/schemas/DefaultResponse'
              example:
                isSuccess: false
                message: Internal server error
                statusCode: 500
                logIdentifier: def456
components:
  securitySchemes:
    apikeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Your API Key.
    XMerchantId:
      type: apiKey
      name: X-MerchantId
      in: header
      description: Your Merchant Identifier (GUID).
      