openapi: '3.0.3'
info:
  title: Transfers Module
  version: '1.0'
servers:
  - url: https://merchantapi.testewallet.com
tags:
  - name: Transfers
security:
  - apikeyAuth: []
paths:
  /api/v{version}/transfer/create:
    post:
      tags:
        - Transfers
      summary: Create a Transfer
      operationId: create-transfer
      requestBody:
        content:
          application/json:
            schema:
              required:
                - merchantTransactionId
                - beneficiaryToken
                - destinationToken
                - dateExpire
                - sourceAmount
                - sourceCurrency
                - destinationCurrency
                - destinationType
              $ref: './schemas/transfer_schemas.yml#/schemas/CreateTransferRequest'
      parameters:
        - $ref: './schemas/index.yml#/parameters/XMerchantId'
        - $ref: './schemas/index.yml#/parameters/Version'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './schemas/index.yml#/schemas/DefaultResponse'
                  - type: object
                    properties:
                      token:
                        type: string
                        description: The token for the created transfer.
                      dateCreated:
                        type: string
                        format: date-time
                        description: The date and time when the transfer was created.
                      dateUpdated:
                        type: string
                        format: date-time
                        description: The date and time when the transfer was last updated.
                      statusId:
                        type: integer
                        description: The status ID of the transfer.
                      fxRate:
                        type: number
                        format: float
                        description: The foreign exchange rate applied to the transfer.
                      customerFee:
                        type: number
                        format: float
                        description: The fee charged to the customer.
                      merchantFee:
                        type: number
                        format: float
                        description: The fee charged to the merchant.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: './schemas/index.yml#/schemas/DefaultResponse'
              example:
                isSuccess: false
                message: Invalid request
                statusCode: 400
                logIdentifier: xyz789
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: './schemas/index.yml#/schemas/DefaultResponse'
              example:
                isSuccess: false
                message: Internal server error
                statusCode: 500
                logIdentifier: def456
  /api/v{version}/transfer/{token}/cancel:
    put:
      tags:
        - Transfers
      summary: Cancel Transfer
      operationId: cancel-transfer
      parameters:
        - $ref: './schemas/index.yml#/parameters/XMerchantId'
        - $ref: './schemas/index.yml#/parameters/Version'
        - $ref: './schemas/transfer_schemas.yml#/parameters/Token'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: './schemas/index.yml#/schemas/DefaultResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: './schemas/index.yml#/schemas/DefaultResponse'
              example:
                isSuccess: false
                message: Invalid request
                statusCode: 400
                logIdentifier: xyz789
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: './schemas/index.yml#/schemas/DefaultResponse'
              example:
                isSuccess: false
                message: Internal server error
                statusCode: 500
                logIdentifier: def456
  /api/v{version}/transfer/{token}/approve:
    put:
      tags:
        - Transfers
      summary: Approve Transfer
      operationId: approve-transfer
      parameters:
        - $ref: './schemas/index.yml#/parameters/XMerchantId'
        - $ref: './schemas/index.yml#/parameters/Version'
        - $ref: './schemas/transfer_schemas.yml#/parameters/Token'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: './schemas/index.yml#/schemas/DefaultResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: './schemas/index.yml#/schemas/DefaultResponse'
              example:
                isSuccess: false
                message: Invalid request
                statusCode: 400
                logIdentifier: xyz789
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: './schemas/index.yml#/schemas/DefaultResponse'
              example:
                isSuccess: false
                message: Internal server error
                statusCode: 500
                logIdentifier: def456
  /api/v{version}/transfer/{token}:
    post:
      tags:
        - Transfers
      summary: Update a Transfer
      operationId: update-transfer
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schemas/transfer_schemas.yml#/schemas/CreateTransferRequest'
      parameters:
        - $ref: './schemas/index.yml#/parameters/XMerchantId'
        - $ref: './schemas/index.yml#/parameters/Version'
        - $ref: './schemas/transfer_schemas.yml#/parameters/Token'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './schemas/index.yml#/schemas/DefaultResponse'
                  - type: object
                    properties:
                      token:
                        type: string
                        description: The token for the created transfer.
                      dateCreated:
                        type: string
                        format: date-time
                        description: The date and time when the transfer was created.
                      dateUpdated:
                        type: string
                        format: date-time
                        description: The date and time when the transfer was last updated.
                      statusId:
                        type: integer
                        description: The status ID of the transfer.
                      fxRate:
                        type: number
                        format: float
                        description: The foreign exchange rate applied to the transfer.
                      customerFee:
                        type: number
                        format: float
                        description: The fee charged to the customer.
                      merchantFee:
                        type: number
                        format: float
                        description: The fee charged to the merchant.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: './schemas/index.yml#/schemas/DefaultResponse'
              example:
                isSuccess: false
                message: Invalid request
                statusCode: 400
                logIdentifier: xyz789
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: './schemas/index.yml#/schemas/DefaultResponse'
              example:
                isSuccess: false
                message: Internal server error
                statusCode: 500
                logIdentifier: def456
  
components:
  securitySchemes:
    apikeyAuth:
      type: apiKey
      in: header
      name: Authorization